type: object
required:
  - enabled
  - defaultValue
  - rules
properties:
  enabled:
    type: boolean
  defaultValue:
    oneOf:
      - type: string
      - type: number
      - type: boolean
  rules:
    type: array
    items:
      $ref: "./FeatureRule.yaml"
  definition:
    type: string
    description: "A JSON stringified [FeatureDefinition](#tag/FeatureDefinition_model)"
  draft:
    type: object
    required:
      - enabled
      - defaultValue
      - rules
    properties:
      enabled:
        type: boolean
      defaultValue:
        oneOf:
          - type: string
          - type: number
          - type: boolean
      rules:
        type: array
        items:
          $ref: "./FeatureRule.yaml"
      definition:
        type: string
        description: "A JSON stringified [FeatureDefinition](#tag/FeatureDefinition_model)"
